### ISSUE TITLE
RcppEigen build failure

### ISSUE THREAD

**Issue by jonathon-love** [RcppCore/RcppEigen#84]
hi dirk,

(insert disclaimer that this may not be the right place to ask these sorts of questions, but i couldn't find anything that seemed more appropriate).

i'm building RcppEigen as part of a flatpak project, but i'm running into a failure with the newer (19.08) sdk. it worked with the older (18.08) sdk. however, i'm not getting any sort of error message to figure out what's going awry.

does this point to it being a host issue? i.e. perhaps its hitting a memory limit? or is my configuration at fault here?

here's the log (the rcppeigen stuff begins at line 4366):

https://ci.appveyor.com/project/jonathon-love/jamovi-library/build/job/ct4m2itq5hpvfs75?fullLog=true

with thanks

**Comment by eddelbuettel** [comment]
Howdy, and no worries, this is the place (or maybe the rcpp-devel list).

But if you have flatpak issues, I fear it is between you and the Gnome folks to sort it out.  I was at a hackathon setup by Ubuntu last year to see what we could do with snap and R, and it turns there were some structural issues there too.  So no mas.  I really only have capacity to support RcppEigen at the normal CRAN level: straight up compilation.  So sorry, those 7000 lines of log messages will have to wait for someone else.  My recommendation is always to narrow it down: try the same compiler in a different setting etc pp in order to triangulate.  Good luck!

**Comment by jonathon-love** [comment]
yup, no worries.

to be clear, i have actually been shipping R and RcppEigen successfully in flatpak projects for at least 18 months now - it's only this SDK change which has caught me out. but i appreciate one has to allocate one's time with discipline.

with thanks

**Comment by eddelbuettel** [comment]
Maybe you can get just the new sdk down into a smaller, more debuggable space like a container and see if it needs a different compiler, or switches, or ...  

Plain RcppEigen appears to still build all the way up from `g++-4` (on Windows and others) to `g++-10` (in tests by Brian Ripley et al) so you need to find the change vector particular to your setup.

**Comment by jonathon-love** [comment]
this was a bug in appveyor. solved by setting the environmental variable:

```
APPVEYOR_CONSOLE_DISABLE_PTY=true
```

what does that environmental variable do? don't know, don't care (actually that's not quite true, i did try and figure it out, but couldn't find any information on it).
